# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'FBSDKCoreKit'  
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBSDKPlacesKit'
pod 'FBSDKMessengerShareKit'

#pod 'RNI18n', :path => '../node_modules/react-native-i18n'


target 'brandprofilingApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for brandprofilingApp

  target 'brandprofilingAppTests' do
    inherit! :search_paths
    #pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

    #pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
    #pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios' 
   # Pods for testing
  end

end

